name: Production environment deployment

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: yarn setup
      - name: Build
        run: yarn build:web
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: Deploy static site to S3 bucket
        run: |
          cd packages/web/dist
          aws s3 sync . s3://comunion-production --delete --acl public-read
          aws cloudfront create-invalidation --distribution-id E1HPMK2YTSD0L1 --paths '/index.html' '/service-worker.js' '/manifest.json'
      - name: Notification
        uses: erguotou520/instant-access-action@0.0.4
        if: ${{ success() }}
        with:
          channel: '3fa27c0affa54c069e428af95f0f98fa'
          head: '{{branchName}} deploy succeed!'
          body: '{{author}} commit "{{commitMessage}}" on {{repositoryName}}#{{branchName}} branch at {{commitTime}}'
      - name: Notification
        uses: erguotou520/instant-access-action@0.0.4
        if: ${{ failure() }}
        with:
          channel: '3fa27c0affa54c069e428af95f0f98fa'
          head: '{{branchName}} deploy failed!'
          body: '{{author}} commit "{{commitMessage}}" on {{repositoryName}}#{{branchName}} branch at {{commitTime}}'
