name: Production environment deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.0.2
      - name: Install dependencies
        run: pnpm i
      - name: Build
        run: pnpm build
        env:
          VITE_SUPPORTED_CHAIN_ID: 43114
          VITE_GITHUB_CLIENT_ID: 'e570640a7b581ed2fd09'
          VITE_GITHUB_CALLBACK_URL: 'https://comunion.org/auth/callback/github'
          VITE_GOOGLE_CLIENT_ID: '963064763183-b8vmgult91p8vguk9ssq6usai7eloor9.apps.googleusercontent.com'
          VITE_GOOGLE_CALLBACK_URL: 'https://comunion.org/auth/callback/google'
      - name: Deploy
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          passphrase: ${{ secrets.PROD_PASSPHRASE }}
          key: ${{ secrets.PROD_KEY }}
          port: ${{ secrets.PROD_PORT }}
          source: 'packages/web/dist/*'
          target: '/app/web/prod'
          strip_components: 3
      - name: Notification
        uses: erguotou520/instant-access-action@0.0.4
        if: ${{ success() }}
        with:
          channel: '3fa27c0affa54c069e428af95f0f98fa'
          head: '{{branchName}} deploy succeed!'
          body: '{{author}} commit "{{commitMessage}}" on {{repositoryName}}#{{branchName}} branch at {{commitTime}}'
      - name: Notification
        uses: erguotou520/instant-access-action@0.0.4
        if: ${{ failure() }}
        with:
          channel: '3fa27c0affa54c069e428af95f0f98fa'
          head: '{{branchName}} deploy failed!'
          body: '{{author}} commit "{{commitMessage}}" on {{repositoryName}}#{{branchName}} branch at {{commitTime}}'
